######################
#### HUGO v0.145.0 ###
######################

baseURL = "https://lulullia.github.io/"
theme = "stack"

title = "Purple Planetarium"
author = "Lulullia"
copyright = "Lulullia"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "#"

[pagination]
  pagerSize = 10

# LANGUAGE
defaultContentLanguage = "en"

[languages]

  [languages.en]
    #contentDir = "content/en"
    disabled = false
    languageCode = "en"
    languageDirection = "ltr"
    languageName = "English"
    params.sidebar.subtitle = "One world, countless stories"

  [languages.fr]
    #contentDir = "content/en"
    disabled = false
    languageCode = "fr"
    languageDirection = "ltr"
    languageName = "Fran√ßais"
    params.sidebar.subtitle = "Un monde, d'innombrables histoires"

# MODULE
[module]

  [[module.mounts]]
      source = "D:/Files/!!NOTES!!/Chaotic Creativity/Moons/Blog"
      target = "content"
  [[module.mounts]]
      source = "content"
      target = "content"

  [[module.mounts]]
      source = "D:/Files/!!NOTES!!/Chaotic Creativity/Storehouse/att/img"
      target = "assets/img"
  [[module.mounts]]
      source = "assets"
      target = "assets"


# PERMALINKS
[permalinks]
  page = "/:slug/"

  blog = "/entry/:year/:slug/"
  artblog = "/entry/:year/art-:slug/"

  world = "/world/:slug/"
  categories = "/world/:slug/"


# TAXONOMIES
[taxonomies]
  category = "categories"
  project = "projects"
  topic = "topics"


# MARKUP
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]
    [markup.goldmark.renderer]
      unsafe = true